update GHA to use Edgee CLI, add icon file

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -46,7 +46,13 @@ jobs:
       - uses: actions-rust-lang/setup-rust-toolchain@v1
         with:
           target: wasm32-wasip2 # WebAssembly target
-      - run: make build
+      - run: edgee component build
+      - name: Verify .wasm file exists
+        run: |
+          if [ ! -f "./kinesis.wasm" ]; then
+              echo "❌ Error: kinesis.wasm not found" >&2
+              exit 1
+          fi
 
   test:
     name: cargo test
